---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: nestedclusters.metal.harvesterhci.io
spec:
  group: metal.harvesterhci.io
  names:
    kind: NestedCluster
    listKind: NestedClusterList
    plural: nestedclusters
    singular: nestedcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: ClusterStatus
      type: string
    - jsonPath: .status.token
      name: ClusterToken
      type: string
    - jsonPath: .status.clusterAddress
      name: ClusterAddress
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Cluster is the Schema for the clusters API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: |-
              NestedClusterSpec defines the state of underlying Cluster object
              generted by the nested cluster controller
            properties:
              clusterConfig:
                properties:
                  bondOptions:
                    additionalProperties:
                      type: string
                    type: object
                  configURL:
                    type: string
                  customProvisioningTemplate:
                    type: string
                  nameservers:
                    items:
                      type: string
                    type: array
                  sshKeys:
                    items:
                      type: string
                    type: array
                  streamImageMode:
                    type: boolean
                  vlanID:
                    default: 1
                    minimum: 1
                    type: integer
                  wipeDisks:
                    type: boolean
                type: object
              imageURL:
                type: string
              inventoryTemplateConfig:
                items:
                  description: |-
                    InventoryTemplateConfig defines the inventory template
                    and eventually geenerates the inventory objects and configures a cluster
                    using the generated inventory and address pool references
                  properties:
                    addressPoolReference:
                      properties:
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                      - name
                      - namespace
                      type: object
                    inventoryTemplateSpec:
                      properties:
                        credentials:
                          description: |-
                            SecretReference represents a Secret Reference. It has enough information to retrieve secret
                            in any namespace
                          properties:
                            name:
                              description: name is unique within a namespace to reference
                                a secret resource.
                              type: string
                            namespace:
                              description: namespace defines the space within which
                                the secret name must be unique.
                              type: string
                          type: object
                          x-kubernetes-map-type: atomic
                        vmSpec:
                          properties:
                            count:
                              default: 1
                              format: int32
                              type: integer
                            cpu:
                              default: 8
                              format: int32
                              type: integer
                            disks:
                              items:
                                properties:
                                  driver:
                                    default: virtio
                                    enum:
                                    - virtio
                                    - sata
                                    - scsi
                                    type: string
                                  size:
                                    anyOf:
                                    - type: integer
                                    - type: string
                                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                                    x-kubernetes-int-or-string: true
                                  storageClass:
                                    type: string
                                required:
                                - driver
                                - size
                                - storageClass
                                type: object
                              type: array
                            ingressClassName:
                              default: nginx
                              type: string
                            memory:
                              anyOf:
                              - type: integer
                              - type: string
                              default: 32Gi
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            namespace:
                              default: default
                              type: string
                            networks:
                              items:
                                description: |-
                                  NetworkConfig allows users to define VMNetworks to be used with nic interfaces in
                                  the underlying kubevirt vm
                                properties:
                                  nicModel:
                                    default: virtio
                                    enum:
                                    - e1000
                                    - e1000e
                                    - igb
                                    - ne2k_pci
                                    - pcnet
                                    - rtl8139
                                    - virtio
                                    type: string
                                  vmNetwork:
                                    type: string
                                required:
                                - nicModel
                                - vmNetwork
                                type: object
                              type: array
                          required:
                          - count
                          - cpu
                          - disks
                          - ingressClassName
                          - memory
                          - namespace
                          - networks
                          type: object
                      required:
                      - credentials
                      - vmSpec
                      type: object
                    name:
                      type: string
                  required:
                  - addressPoolReference
                  - inventoryTemplateSpec
                  - name
                  type: object
                type: array
              version:
                type: string
              vipConfig:
                properties:
                  addressPoolReference:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                  staticAddress:
                    type: string
                required:
                - addressPoolReference
                type: object
            required:
            - clusterConfig
            - imageURL
            - inventoryTemplateConfig
            - version
            - vipConfig
            type: object
          status:
            description: ClusterStatus defines the observed state of Cluster
            properties:
              clusterAddress:
                type: string
              status:
                type: string
              token:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
