---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {}
  name: inventorytemplates.metal.harvesterhci.io
spec:
  group: metal.harvesterhci.io
  names:
    kind: InventoryTemplate
    listKind: InventoryTemplateList
    plural: inventorytemplates
    singular: inventorytemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: InventoryTemplateStatus
      type: string
    - jsonPath: .status.message
      name: Reason
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: InventoryTemplate is the Schema for the InventoryTemplate API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              credentials:
                description: |-
                  SecretReference represents a Secret Reference. It has enough information to retrieve secret
                  in any namespace
                properties:
                  name:
                    description: name is unique within a namespace to reference a
                      secret resource.
                    type: string
                  namespace:
                    description: namespace defines the space within which the secret
                      name must be unique.
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              vmSpec:
                properties:
                  count:
                    default: 1
                    format: int32
                    type: integer
                  cpu:
                    default: 8
                    format: int32
                    type: integer
                  disks:
                    items:
                      properties:
                        driver:
                          default: virtio
                          enum:
                          - virtio
                          - sata
                          - scsi
                          type: string
                        size:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        storageClass:
                          type: string
                      required:
                      - driver
                      - size
                      - storageClass
                      type: object
                    type: array
                  ingressClassName:
                    default: nginx
                    type: string
                  memory:
                    anyOf:
                    - type: integer
                    - type: string
                    default: 32Gi
                    pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                    x-kubernetes-int-or-string: true
                  namespace:
                    default: default
                    type: string
                  networks:
                    items:
                      description: |-
                        NetworkConfig allows users to define VMNetworks to be used with nic interfaces in
                        the underlying kubevirt vm
                      properties:
                        nicModel:
                          default: virtio
                          enum:
                          - e1000
                          - e1000e
                          - igb
                          - ne2k_pci
                          - pcnet
                          - rtl8139
                          - virtio
                          type: string
                        vmNetwork:
                          type: string
                      required:
                      - nicModel
                      - vmNetwork
                      type: object
                    type: array
                required:
                - count
                - cpu
                - disks
                - ingressClassName
                - memory
                - namespace
                - networks
                type: object
            required:
            - credentials
            - vmSpec
            type: object
          status:
            properties:
              message:
                type: string
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
