stack:
  hook:
    enabled: true
    name: hook-files
    port: 8080
    image: bash
    downloadsDest: /opt/hook
    # downloadURL only works with the > 0.8.1 Hook release because
    # previous Hook versions didn't provide a checksum file.
    downloadURL: https://github.com/tinkerbell/hook/releases/download/v0.8.1
# -- Overrides
# The values defined here override those in the individual charts. Some of them require tweaking
# before deployment as they are environment dependent; others are surfaced for convenience.
#
# See individual chart documentation for additional detail.
podCIDR: &range ["10.42.0.0/24"]
publicIP: &publicIP "$(PUBLIC_IP)"
smee:
  image: quay.io/tinkerbell/smee:v0.15.2
  tinkWorkerImage: quay.io/tinkerbell/tink-worker:v0.12.2
  trustedProxies: *range
  publicIP: *publicIP
  hostNetwork: true
  deployment:
    strategy:
      type: Recreate

hegel:
  image: quay.io/tinkerbell/hegel:v0.14.2
  trustedProxies: *range

rufio:
  image: quay.io/tinkerbell/rufio:v0.6.5

tink:
  controller:
    image: quay.io/tinkerbell/tink-controller:v0.12.2
  server:
    image: quay.io/tinkerbell/tink:v0.12.2
